#!/bin/bash
rm -rf dist
export PYTHONHASHSEED=22
VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii contrib/osx.spec
hdiutil create -fs HFS+ -volname "Electrum-zeny" -srcfolder dist/Electrum.app dist/electrum-$VERSION.dmg

